# pull official base image
FROM node:alpine

# set working directory
WORKDIR /app

# add app
COPY . .


# install app dependencies
RUN npm install 

RUN npm run build

# start app
CMD ["npm", "start"]





